export const INITIALIZE_STATE ='INITIALIZE_STATE';
export const INITIALIZE_GRAPH_NUMBER = 'INITIALIZE_GRAPH_NUMBER'
export const INCREMENT_GRAPH_NUMBER = 'INCREMENT_GRAPH_NUMBER';
export const DECREMENT_GRAPH_NUMBER = 'DECREMENT_GRAPH_NUMBER';
export const UPDATE_FIRST_DATASET = 'UPDATE_FIRST_DATASET';
export const UPDATE_SECOND_DATASET = 'UPDATE_SECOND_DATASET';
export const DELETE_FIRST_DATASET = 'DELETE_FIRST_DATASET';
export const DELETE_SECOND_DATASET = 'DELETE_SECOND_DATASET';
export const UPDATE_DATAPOINTS = 'UPDATE_DATAPOINTS';
export const UPDATE_DATES = 'UPDATE_DATES';
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';


